spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false
  
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

logging:
  level:
    br.com.api.creditos: WARN
    org.springframework.kafka: WARN
    org.hibernate: WARN
    org.testcontainers: WARN

server:
  port: 0  # Random port for tests

