spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditos_db
    username: ${DB_USERNAME:creditos_user}
    password: ${DB_PASSWORD:creditos_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    br.com.api.creditos: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/api-creditos-dev.log

server:
  port: 8080

