-- Criação da tabela de créditos
CREATE TABLE credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_credito VARCHAR(50) NOT NULL,
    numero_nfse VARCHAR(50) NOT NULL,
    data_constituicao DATE NOT NULL,
    valor_issqn DECIMAL(15, 2) NOT NULL,
    tipo_credito VARCHAR(50) NOT NULL,
    simples_nacional BOOLEAN NOT NULL,
    aliquota DECIMAL(5, 2) NOT NULL,
    valor_faturado DECIMAL(15, 2) NOT NULL,
    valor_deducao DECIMAL(15, 2) NOT NULL,
    base_calculo DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para otimizar consultas
CREATE INDEX idx_credito_numero_credito ON credito(numero_credito);
CREATE INDEX idx_credito_numero_nfse ON credito(numero_nfse);
CREATE INDEX idx_credito_data_constituicao ON credito(data_constituicao);
CREATE INDEX idx_credito_tipo_credito ON credito(tipo_credito);

-- Comentários para documentação
COMMENT ON TABLE credito IS 'Tabela de créditos constituídos';
COMMENT ON COLUMN credito.numero_credito IS 'Número identificador único do crédito constituído';
COMMENT ON COLUMN credito.numero_nfse IS 'Número da Nota Fiscal de Serviços Eletrônica';
COMMENT ON COLUMN credito.data_constituicao IS 'Data de constituição do crédito';
COMMENT ON COLUMN credito.valor_issqn IS 'Valor do Imposto Sobre Serviços de Qualquer Natureza';
COMMENT ON COLUMN credito.tipo_credito IS 'Tipo do crédito (ISSQN, Outros, etc.)';
COMMENT ON COLUMN credito.simples_nacional IS 'Indica se é optante pelo Simples Nacional';
COMMENT ON COLUMN credito.aliquota IS 'Alíquota aplicada no cálculo do imposto';
COMMENT ON COLUMN credito.valor_faturado IS 'Valor total faturado';
COMMENT ON COLUMN credito.valor_deducao IS 'Valor das deduções aplicadas';
COMMENT ON COLUMN credito.base_calculo IS 'Base de cálculo para o imposto';

